eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/,http://localhost:9761/eureka/
server:
    port: 8765
spring:
    application:
        name: demo-feign
#Feign是自带断路器的，在D版本的Spring Cloud中，它没有默认打开
feign:
    hystrix:
        enabled: true
