eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/,http://localhost:9761/eureka/
server:
    port: 8764
spring:
    application:
        name: demo-ribbon

