eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/,http://localhost:9761/eureka/
server:
    port: 8769
spring:
    application:
        name: demo-zuul
zuul:
    routes:
        api-a:
            path: /api-a/**
            serviceId: demo-ribbon
        api-b:
            path: /api-b/**
            serviceId: demo-feign

